# Generated by Django 5.0.6 on 2024-07-30 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=100)),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.deportista')),
            ],
        ),
        migrations.DeleteModel(
            name='Datos',
        ),
    ]
