# Generated by Django 5.0.6 on 2024-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
        ('campeonato', '0002_campeonato_delete_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('disiplina', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('nr_participantes', models.IntegerField()),
                ('participantes', models.ManyToManyField(to='Persona.deportista')),
            ],
        ),
    ]
