# Generated by Django 5.0.6 on 2024-07-30 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0003_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nr_participantes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
