# Generated by Django 5.0.6 on 2024-07-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campeonato', '0004_alter_equipo_nr_participantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPosisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100)),
                ('puntos', models.IntegerField()),
                ('partidos_jugados', models.IntegerField()),
                ('partidos_ganados', models.IntegerField()),
                ('partidos_empatados', models.IntegerField()),
                ('partidos_perdidos', models.IntegerField()),
                ('goles_favor', models.IntegerField()),
                ('goles_contra', models.IntegerField()),
                ('diferencia_goles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.IntegerField()),
                ('goles_visitante', models.IntegerField()),
                ('fecha', models.DateField()),
                ('equipo_local', models.ManyToManyField(related_name='encuentros_locales', to='campeonato.equipo')),
                ('equipo_visitante', models.ManyToManyField(related_name='encuentros_visitantes', to='campeonato.equipo')),
            ],
        ),
    ]
