# Generated by Django 5.0.6 on 2024-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0004_alter_equipo_nr_participantes'),
        ('tablaPosisiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empate', models.BooleanField()),
                ('equipo_ganador', models.ManyToManyField(related_name='resultados_ganados', to='campeonato.equipo')),
                ('equipo_perdedor', models.ManyToManyField(related_name='resultados_perdidos', to='campeonato.equipo')),
            ],
        ),
    ]
